/**
 * Instruction candidate patterns.
 *
 * Regex patterns used to decide whether a line in an instruction file
 * looks like it contains a verifiable instruction (imperative statement,
 * requirement, or constraint) rather than documentation prose.
 *
 * Extracted from rule-extractor.ts to keep that file under the 300-line limit.
 */

/**
 * Patterns that identify instruction-like lines.
 *
 * If any pattern matches a line, it is treated as a candidate for rule extraction.
 * Non-matching lines are classified as prose and silently skipped.
 */
export const INSTRUCTION_PATTERNS: RegExp[] = [
  /^[-*+]\s+/,                     // unordered list item
  /^\d+\.\s+/,                     // ordered list item
  /\b(must|should|always|never|no|don'?t|avoid|use|require|ensure)\b/i,
  /\b(camel|pascal|kebab|snake)[\s-]*case\b/i,
  /\bconsole\.?\w*\b/i,
  /\bdefault\s+export/i,
  /\bany\s+type/i,
  /\bJSDoc\b/i,
  /\bstrict\s+mode\b/i,
  /\btest\s+file/i,
  /\brelative\s+import/i,
  /\bpath\s+alias/i,
  /\bmax(?:imum)?\s+(?:line|file|function|param(?:eter)?s?)\b/i,
  /\b(?:line|file)\s+length\b/i,
  /\bnamed\s+export/i,
  /\bempty\s+catch\b/i,
  /\benums?\b/i,
  /\btype\s+assertions?\b/i,
  /\bnon[\s-]null\s+assertion/i,
  /\bthrow\b/i,
  /\bternary\b/i,
  /\bmagic\s+numbers?\b/i,
  /\belse\s+after\s+return\b/i,
  /\bearly\s+returns?\b/i,
  /\bnamespace\s+imports?\b/i,
  /\bimport\s+\*/i,
  /\bbarrel\s+(?:files?|exports?)\b/i,
  /\bsetTimeout\b/i,
  /\b@?ts[\s-](?:ignore|nocheck|expect)/i,
  /\b\.only\s*\(/i,
  /\b\.skip\s*\(/i,
  /\bfocused\s+tests?\b/i,
  /\bskipped\s+tests?\b/i,
  /\bsingle\s+quotes?\b/i,
  /\bbanned?\s+(?:package|import|library)\b/i,
  /\bREADME\b/i,
  /\bCHANGELOG\b/i,
  /\bformatter\b/i,
  /\bprettier\b/i,
  /\beslint\b/i,
  /\bbiome\b/i,
  /\bpin(?:ned)?\s+(?:dependenc|version)/i,
  /\bexact\s+versions?\b/i,
  /\bswallow(?:ed)?\s+(?:error|exception)/i,
  /\bsilent\s+(?:failure|catch)\b/i,
  /\bwildcard\s+imports?\b/i,
  /\bprefer\s+const\b/i,
  /\bconst\s+over\s+let\b/i,
  /\bimmutable\s+by\s+default\b/i,
  /\bno\s+var\b/i,
  /\bwildcard\s+(?:re-?)?exports?\b/i,
  /\bexport\s*\*\b/i,
  /\bTODO\b.*\bnot\s+allowed\b/i,
  /\bno\s+TODO\b/i,
  /\bsemicolon/i,
  /\bimplicit\s+any\b/i,
  /\bunused\s+exports?\b/i,
  /\bunresolved\s+imports?\b/i,
  /\bpython\b.*\bsnake/i,
  /\bgo\b.*\bnaming/i,
  /\bkebab[\s-]*case\b.*\b(?:director|folder)/i,
  /\blowercase\s+with\s+dashes?\b.*\b(?:director|folder)/i,
  /\bconcise\s+(?:syntax|conditional)/i,
  /\bavoid\b.*\bcurly\s+braces?\b/i,
  /\bunnecessary\s+(?:curly\s+)?braces?/i,
  /\bprefer\b.*\bover\b/i,
  /\bfavor\b.*\bover\b/i,
  /\binstead\s+of\b/i,
  /\bprefer\s+(?:functional|named|interface|async|arrow|template|optional)\b/i,
  /\bfunctional\s+component/i,
  /\bclass\s+component/i,
  /\boptional\s+chaining\b/i,
  /\btemplate\s+literal/i,
  /\basync\s*\/?\s*await\b/i,
  /\b(?:pnpm|yarn|bun)\b/i,
  /\bvitest\b/i,
  /\bjest\b/i,
  /\bpytest\b/i,
  /\bunittest\b/i,
  /\blockfile\b/i,
  /\bcolocat(?:e|ed|ion)\b/i,
  /\bdescribe\s*\/?\s*it\s+blocks?\b/i,
  /\bdescribe\s+blocks?\b/i,
  /\btest\s+framework\b/i,
  /\b__tests__\b/i,
  /\bsrc\//i,
  /\bindex\.ts\b/i,
  /\b\.env\b/i,
];
