/**
 * Config-file rule matchers.
 *
 * Matches instructions about CI/CD, git hooks, npm scripts,
 * and environment tool requirements.
 */

import type { RuleMatcher } from '../types.js';

/** Matchers for rules verifiable via config file inspection. */
export const CONFIG_FILE_MATCHERS: RuleMatcher[] = [
  {
    id: 'config-ci-lint',
    patterns: [
      /\bCI\b.*\b(?:run|execut)\w*\s+(?:lint|eslint|biome)/i,
      /\b(?:lint|eslint|biome)\b.*\b(?:in\s+)?CI\b/i,
      /\bpipeline\b.*\b(?:lint|eslint)/i,
      /\bgithub\s+actions?\b.*\b(?:lint)/i,
    ],
    category: 'workflow',
    verifier: 'config-file',
    description: 'CI pipeline must run lint checks',
    severity: 'warning',
    confidence: 'medium',
    buildPattern: () => ({
      type: 'ci-command-present',
      target: 'lint',
      expected: true,
      scope: 'project',
    }),
  },
  {
    id: 'config-ci-test',
    patterns: [
      /\bCI\b.*\b(?:run|execut)\w*\s+(?:test|spec)/i,
      /\btests?\b.*\b(?:in\s+)?CI\b/i,
      /\bpipeline\b.*\btests?\b/i,
      /\bgithub\s+actions?\b.*\b(?:test)/i,
    ],
    category: 'workflow',
    verifier: 'config-file',
    description: 'CI pipeline must run tests',
    severity: 'warning',
    confidence: 'medium',
    buildPattern: () => ({
      type: 'ci-command-present',
      target: 'test',
      expected: true,
      scope: 'project',
    }),
  },
  {
    id: 'config-ci-typecheck',
    patterns: [
      /\bCI\b.*\b(?:run|execut)\w*\s+(?:type\s*check|tsc)/i,
      /\btype\s*check\b.*\b(?:in\s+)?CI\b/i,
    ],
    category: 'workflow',
    verifier: 'config-file',
    description: 'CI pipeline must run type checking',
    severity: 'warning',
    confidence: 'medium',
    buildPattern: () => ({
      type: 'ci-command-present',
      target: 'tsc',
      expected: true,
      scope: 'project',
    }),
  },
  {
    id: 'config-ci-present',
    patterns: [
      /\bset\s+up\s+CI\b/i,
      /\bconfigure\s+CI\b/i,
      /\b(?:must|should)\s+(?:have|include)\s+CI\b/i,
      /\bgithub\s+actions?\s+workflow/i,
    ],
    category: 'workflow',
    verifier: 'config-file',
    description: 'Project must have CI configuration',
    severity: 'warning',
    confidence: 'medium',
    buildPattern: () => ({
      type: 'ci-config-present',
      target: 'ci',
      expected: true,
      scope: 'project',
    }),
  },
  {
    id: 'config-pre-commit-test',
    patterns: [
      /\brun\s+(?:npm\s+)?test\s+(?:before|prior\s+to)\s+commit/i,
      /\bpre[- ]commit\b.*\btest/i,
      /\btest\b.*\bpre[- ]commit\b/i,
      /\bbefore\s+commit(?:ting)?\b.*\brun\s+(?:the\s+)?tests?\b/i,
    ],
    category: 'workflow',
    verifier: 'config-file',
    description: 'Pre-commit hook must run tests',
    severity: 'warning',
    confidence: 'medium',
    buildPattern: () => ({
      type: 'pre-commit-check',
      target: 'test',
      expected: true,
      scope: 'project',
    }),
  },
  {
    id: 'config-pre-commit-lint',
    patterns: [
      /\brun\s+(?:npm\s+)?lint\s+(?:before|prior\s+to)\s+commit/i,
      /\bpre[- ]commit\b.*\blint/i,
      /\blint\b.*\bpre[- ]commit\b/i,
      /\bbefore\s+commit(?:ting)?\b.*\brun\s+(?:the\s+)?lint/i,
    ],
    category: 'workflow',
    verifier: 'config-file',
    description: 'Pre-commit hook must run linting',
    severity: 'warning',
    confidence: 'medium',
    buildPattern: () => ({
      type: 'pre-commit-check',
      target: 'lint',
      expected: true,
      scope: 'project',
    }),
  },
  {
    id: 'config-husky',
    patterns: [
      /\buse\s+husky\b/i,
      /\bhusky\b.*\bgit\s+hooks?\b/i,
      /\bgit\s+hooks?\b.*\bhusky\b/i,
      /\bset\s+up\s+husky\b/i,
    ],
    category: 'workflow',
    verifier: 'config-file',
    description: 'Project must use husky for git hooks',
    severity: 'warning',
    confidence: 'high',
    buildPattern: () => ({
      type: 'git-hook-present',
      target: 'pre-commit',
      expected: true,
      scope: 'project',
    }),
  },
  {
    id: 'config-lefthook',
    patterns: [
      /\buse\s+lefthook\b/i,
      /\blefthook\b.*\bgit\s+hooks?\b/i,
    ],
    category: 'workflow',
    verifier: 'config-file',
    description: 'Project must use lefthook for git hooks',
    severity: 'warning',
    confidence: 'high',
    buildPattern: () => ({
      type: 'git-hook-present',
      target: 'pre-commit',
      expected: true,
      scope: 'project',
    }),
  },
  {
    id: 'config-script-test',
    patterns: [
      /\bpackage\.json\b.*\btest\s+script\b/i,
      /\b(?:add|include|define)\s+(?:a\s+)?(?:npm\s+)?test\s+script\b/i,
      /\b(?:npm|yarn|pnpm)\s+test\b.*\bmust\s+(?:be\s+)?(?:defined|present|configured)\b/i,
    ],
    category: 'workflow',
    verifier: 'config-file',
    description: 'package.json must have a test script',
    severity: 'warning',
    confidence: 'medium',
    buildPattern: () => ({
      type: 'script-present',
      target: 'test',
      expected: true,
      scope: 'project',
    }),
  },
  {
    id: 'config-script-lint',
    patterns: [
      /\bpackage\.json\b.*\blint\s+script\b/i,
      /\b(?:add|include|define)\s+(?:a\s+)?(?:npm\s+)?lint\s+script\b/i,
    ],
    category: 'workflow',
    verifier: 'config-file',
    description: 'package.json must have a lint script',
    severity: 'warning',
    confidence: 'medium',
    buildPattern: () => ({
      type: 'script-present',
      target: 'lint',
      expected: true,
      scope: 'project',
    }),
  },
  {
    id: 'config-env-flox',
    patterns: [
      /\buse\s+flox\b/i,
      /\bflox\s+(?:environment|dev|shell)\b/i,
      /\benvironment\b.*\bflox\b/i,
    ],
    category: 'tooling',
    verifier: 'config-file',
    description: 'Project must use flox for environment management',
    severity: 'warning',
    confidence: 'high',
    buildPattern: () => ({
      type: 'env-tool-present',
      target: 'flox',
      expected: true,
      scope: 'project',
    }),
  },
  {
    id: 'config-env-nix',
    patterns: [
      /\buse\s+nix\b/i,
      /\bnix\s+(?:shell|flake|develop)\b/i,
      /\bnix\b.*\benvironment\b/i,
    ],
    category: 'tooling',
    verifier: 'config-file',
    description: 'Project must use nix for environment management',
    severity: 'warning',
    confidence: 'high',
    buildPattern: () => ({
      type: 'env-tool-present',
      target: 'nix',
      expected: true,
      scope: 'project',
    }),
  },
  {
    id: 'config-env-devcontainer',
    patterns: [
      /\buse\s+devcontainer/i,
      /\bdev\s*container\b.*\bconfigure/i,
      /\bconfigure\b.*\bdev\s*container/i,
    ],
    category: 'tooling',
    verifier: 'config-file',
    description: 'Project must have devcontainer configuration',
    severity: 'warning',
    confidence: 'high',
    buildPattern: () => ({
      type: 'env-tool-present',
      target: 'devcontainer',
      expected: true,
      scope: 'project',
    }),
  },
  {
    id: 'config-env-mise',
    patterns: [
      /\buse\s+mise\b/i,
      /\bmise\b.*\btool\s+versions?\b/i,
    ],
    category: 'tooling',
    verifier: 'config-file',
    description: 'Project must use mise for tool version management',
    severity: 'warning',
    confidence: 'high',
    buildPattern: () => ({
      type: 'env-tool-present',
      target: 'mise',
      expected: true,
      scope: 'project',
    }),
  },
  {
    id: 'config-env-volta',
    patterns: [
      /\buse\s+volta\b/i,
      /\bvolta\b.*\bpin\b/i,
      /\bpin\b.*\bvolta\b/i,
    ],
    category: 'tooling',
    verifier: 'config-file',
    description: 'Project must use volta for Node.js version management',
    severity: 'warning',
    confidence: 'high',
    buildPattern: () => ({
      type: 'env-tool-present',
      target: 'volta',
      expected: true,
      scope: 'project',
    }),
  },
];
