/**
 * ESLint config emitter.
 *
 * Serializes an EslintConfig to a runnable ESLint configuration string.
 * Supports flat config (default) and legacy .eslintrc format.
 *
 * Unmappable rules are emitted as commented sections with the original
 * instruction text and a one-line reason explaining why no ESLint rule
 * can enforce them.
 */

import type { EslintConfig, EslintFormat, EslintRuleEntry } from '../mapper/types.js';

/** Map ESLint plugin names to their npm package identifiers. */
const PLUGIN_PACKAGES: Record<string, string> = {
  '@typescript-eslint': '@typescript-eslint/eslint-plugin',
  'import': 'eslint-plugin-import',
  'unicorn': 'eslint-plugin-unicorn',
  'jsdoc': 'eslint-plugin-jsdoc',
};

/** Convert an EslintSeverity to the value used in flat config rule entries. */
function severityValue(severity: 'error' | 'warn'): 'error' | 'warn' {
  return severity;
}

/** Format a rule option value for JS output. */
function formatOptionValue(value: unknown, indent: string): string {
  if (value === null || value === undefined) {
    return 'null';
  }
  if (typeof value === 'string') {
    return `'${value.replace(/'/g, "\\'")}'`;
  }
  if (typeof value === 'number' || typeof value === 'boolean') {
    return String(value);
  }
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    const items = value.map((v) => formatOptionValue(v, indent));
    return `[${items.join(', ')}]`;
  }
  if (typeof value === 'object') {
    const obj = value as Record<string, unknown>;
    const entries = Object.entries(obj);
    if (entries.length === 0) return '{}';
    const inner = entries
      .map(([key, val]) => `${indent}  ${key}: ${formatOptionValue(val, indent + '  ')}`)
      .join(',\n');
    return `{\n${inner}\n${indent}}`;
  }
  return String(value);
}

/** Build a flat config rule entry string. */
function flatConfigRuleEntry(entry: EslintRuleEntry): string {
  const severity = severityValue(entry.severity);
  if (entry.options && Array.isArray(entry.options) && entry.options.length > 0) {
    const opts = entry.options.map((o) => formatOptionValue(o, '      ')).join(', ');
    return `['${entry.ruleName}', ${severity}, ${opts}]`;
  }
  return `['${entry.ruleName}', ${severity}]`;
}

/** Build a legacy .eslintrc rule entry string. */
function legacyConfigRuleEntry(entry: EslintRuleEntry): string {
  const severity = severityValue(entry.severity);
  if (entry.options && Array.isArray(entry.options) && entry.options.length > 0) {
    const opts = entry.options.map((o) => formatOptionValue(o, '    ')).join(', ');
    return `    "${entry.ruleName}": [${severity}, ${opts}]`;
  }
  return `    "${entry.ruleName}": "${severity}"`;
}

/** Generate a flat config import section for required plugins. */
function flatConfigImports(plugins: string[]): string {
  if (plugins.length === 0) return '';

  const lines: string[] = [];
  for (const plugin of plugins) {
    const pkg = PLUGIN_PACKAGES[plugin] ?? plugin;
    lines.push(`import ${plugin.replace(/[^a-zA-Z0-9]/g, '_')}Plugin from '${pkg}';`);
  }
  return lines.join('\n') + '\n\n';
}

/** Generate plugin object entries for flat config. */
function flatConfigPluginEntries(plugins: string[]): string {
  if (plugins.length === 0) return '';

  const entries = plugins.map((p) => {
    const varName = p.replace(/[^a-zA-Z0-9]/g, '_');
    return `    ...${varName}Plugin.configs?.recommended ?? {},`;
  });
  return entries.join('\n') + '\n';
}

/** Build the flat config output string. */
function emitFlatConfig(config: EslintConfig): string {
  const lines: string[] = [];

  // Header comment
  lines.push('// ESLint flat config generated by RuleProbe');
  lines.push(`// Source: ${config.sourceFile}`);
  lines.push('');

  // Imports for plugins
  if (config.plugins.length > 0) {
    lines.push(flatConfigImports(config.plugins));
  }

  // Config export
  lines.push('export default [');
  lines.push('  {');

  // Plugin entries
  if (config.plugins.length > 0) {
    lines.push(flatConfigPluginEntries(config.plugins));
  }

  // Rules
  lines.push('    rules: {');
  for (let i = 0; i < config.rules.length; i++) {
    const entry = config.rules[i]!;
    const entryStr = flatConfigRuleEntry(entry);
    const comma = i < config.rules.length - 1 ? ',' : '';
    lines.push(`      ${entryStr}${comma}  // ${entry.description}`);
  }
  lines.push('    },');
  lines.push('  },');
  lines.push('];');

  // Unmappable rules as comments
  if (config.unmappable.length > 0) {
    lines.push('');
    lines.push('// ── Unmappable rules ──');
    lines.push('// The following rules from your instruction file have no direct');
    lines.push('// ESLint equivalent. Consider alternative enforcement approaches.');
    lines.push('');
    for (const rule of config.unmappable) {
      lines.push(`// [${rule.sourceRuleId}] ${rule.reason}`);
      lines.push(`//   Original: ${rule.sourceText}`);
      lines.push('');
    }
  }

  return lines.join('\n');
}

/** Build the legacy .eslintrc output string. */
function emitLegacyConfig(config: EslintConfig): string {
  const lines: string[] = [];

  lines.push('{');
  lines.push('  // Generated by RuleProbe from: ' + config.sourceFile);
  lines.push('');

  // Plugins
  if (config.plugins.length > 0) {
    lines.push('  "plugins": [');
    for (const plugin of config.plugins) {
      lines.push(`    "${plugin}",`);
    }
    lines.push('  ],');
    lines.push('');
  }

  // Extends
  if (config.plugins.length > 0) {
    lines.push('  "extends": [');
    lines.push('    "eslint:recommended"');
    for (const plugin of config.plugins) {
      lines.push(`    ,"plugin:${plugin}/recommended"`);
    }
    lines.push('  ],');
    lines.push('');
  }

  // Rules
  lines.push('  "rules": {');
  for (let i = 0; i < config.rules.length; i++) {
    const entry = config.rules[i]!;
    const entryStr = legacyConfigRuleEntry(entry);
    const comma = i < config.rules.length - 1 ? ',' : '';
    lines.push(`${entryStr}${comma}  // ${entry.description}`);
  }
  lines.push('  }');

  // Unmappable rules as comments
  if (config.unmappable.length > 0) {
    lines.push(',');
    lines.push('  // Unmappable rules:');
    lines.push('  // The following rules have no direct ESLint equivalent.');
    lines.push('');
    for (const rule of config.unmappable) {
      lines.push(`  // [${rule.sourceRuleId}] ${rule.reason}`);
      lines.push(`  //   Original: ${rule.sourceText}`);
    }
  }

  lines.push('}');
  return lines.join('\n');
}

/**
 * Serialize an EslintConfig to a runnable ESLint configuration string.
 *
 * @param config - The mapped ESLint config
 * @param format - Output format: 'flat' (default) or 'legacy'
 * @returns A string containing the ESLint configuration
 */
export function emitEslintConfig(config: EslintConfig, format: EslintFormat = 'flat'): string {
  if (format === 'legacy') {
    return emitLegacyConfig(config);
  }
  return emitFlatConfig(config);
}