/**
 * ESLint config emitter.
 *
 * Serializes an EslintConfig to a runnable ESLint configuration string.
 * Supports flat config (default) and legacy .eslintrc format.
 *
 * Flat config emits valid ES module JavaScript that can be imported by
 * ESLint. Unmappable rules are appended as JS comments, which remain
 * valid JavaScript.
 *
 * Legacy config emits strictly valid JSON suitable for .eslintrc.json
 * files. Unmappable rules are not included in the JSON output because
 * JSON has no comment syntax; callers should surface them through a
 * sidecar channel via formatUnmappableSummary().
 */

import type { EslintConfig, EslintFormat, EslintRuleEntry } from '../mapper/types.js';

/** Map ESLint plugin names to their npm package identifiers. */
const PLUGIN_PACKAGES: Record<string, string> = {
  '@typescript-eslint': '@typescript-eslint/eslint-plugin',
  'import': 'eslint-plugin-import',
  'unicorn': 'eslint-plugin-unicorn',
  'jsdoc': 'eslint-plugin-jsdoc',
};

/** Format a rule option value for JS output. */
function formatOptionValue(value: unknown, indent: string): string {
  if (value === null || value === undefined) {
    return 'null';
  }
  if (typeof value === 'string') {
    return `'${value.replace(/'/g, "\\'")}'`;
  }
  if (typeof value === 'number' || typeof value === 'boolean') {
    return String(value);
  }
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    const items = value.map((v) => formatOptionValue(v, indent));
    return `[${items.join(', ')}]`;
  }
  if (typeof value === 'object') {
    const obj = value as Record<string, unknown>;
    const entries = Object.entries(obj);
    if (entries.length === 0) return '{}';
    const inner = entries
      .map(([key, val]) => `${indent}  ${key}: ${formatOptionValue(val, indent + '  ')}`)
      .join(',\n');
    return `{\n${inner}\n${indent}}`;
  }
  return String(value);
}

/** Build a flat config rule entry string as an object property. */
function flatConfigRuleEntry(entry: EslintRuleEntry): string {
  const severity = `'${entry.severity}'`;
  if (entry.options && Array.isArray(entry.options) && entry.options.length > 0) {
    const opts = entry.options.map((o) => formatOptionValue(o, '      ')).join(', ');
    return `'${entry.ruleName}': [${severity}, ${opts}]`;
  }
  return `'${entry.ruleName}': [${severity}]`;
}

/** Build a legacy .eslintrc rule entry string as a JSON property. */
function legacyConfigRuleEntry(entry: EslintRuleEntry): string {
  const severity = entry.severity;
  if (entry.options && Array.isArray(entry.options) && entry.options.length > 0) {
    const opts = entry.options.map((o) => JSON.stringify(o)).join(', ');
    return `    "${entry.ruleName}": [${JSON.stringify(severity)}, ${opts}]`;
  }
  return `    "${entry.ruleName}": ${JSON.stringify(severity)}`;
}

/** Generate a flat config import section for required plugins. */
function flatConfigImports(plugins: string[]): string {
  if (plugins.length === 0) return '';

  const lines: string[] = [];
  for (const plugin of plugins) {
    const pkg = PLUGIN_PACKAGES[plugin] ?? plugin;
    lines.push(`import ${plugin.replace(/[^a-zA-Z0-9]/g, '_')}Plugin from '${pkg}';`);
  }
  return lines.join('\n') + '\n\n';
}

/** Generate plugin object entries for flat config. */
function flatConfigPluginEntries(plugins: string[]): string {
  if (plugins.length === 0) return '';

  const entries = plugins.map((p) => {
    const varName = p.replace(/[^a-zA-Z0-9]/g, '_');
    // Property keys with special chars need quotes
    const key = /^[$_a-zA-Z][$_a-zA-Z0-9]*$/.test(p) ? p : `'${p}'`;
    return `      ${key}: ${varName}Plugin,`;
  });
  return entries.join('\n') + '\n';
}

/** Build the flat config output string. */
function emitFlatConfig(config: EslintConfig): string {
  const lines: string[] = [];

  // Header comment
  lines.push('// ESLint flat config generated by RuleProbe');
  lines.push(`// Source: ${config.sourceFile}`);
  lines.push('');

  // Imports for plugins
  if (config.plugins.length > 0) {
    lines.push(flatConfigImports(config.plugins));
  }

  // Config export
  lines.push('export default [');
  lines.push('  {');

  // Plugin entries as an object
  if (config.plugins.length > 0) {
    lines.push('    plugins: {');
    lines.push(flatConfigPluginEntries(config.plugins));
    lines.push('    },');
  }

  // Rules
  lines.push('    rules: {');
  for (let i = 0; i < config.rules.length; i++) {
    const entry = config.rules[i]!;
    const entryStr = flatConfigRuleEntry(entry);
    const comma = i < config.rules.length - 1 ? ',' : '';
    lines.push(`      ${entryStr}${comma}  // ${entry.description}`);
  }
  lines.push('    },');
  lines.push('  },');
  lines.push('];');

  // Unmappable rules as comments
  if (config.unmappable.length > 0) {
    lines.push('');
    lines.push('// ── Unmappable rules ──');
    lines.push('// The following rules from your instruction file have no direct');
    lines.push('// ESLint equivalent. Consider alternative enforcement approaches.');
    lines.push('');
    for (const rule of config.unmappable) {
      lines.push(`// [${rule.sourceRuleId}] ${rule.reason}`);
      lines.push(`//   Original: ${rule.sourceText}`);
      lines.push('');
    }
  }

  return lines.join('\n');
}

/** Build the legacy .eslintrc output string as valid JSON. */
function emitLegacyConfig(config: EslintConfig): string {
  // Build the config as a plain object, then serialize to JSON
  const configObj: Record<string, unknown> = {};

  // Plugins
  if (config.plugins.length > 0) {
    configObj['plugins'] = config.plugins;
  }

  // No automatic `extends` block. The flat config emitter does not add
  // one and emitting eslint:recommended plus plugin recommended sets
  // here would enable hundreds of unrelated rules. Users who want
  // recommended sets can extend them in their own config.

  // Rules as an object with severity + options
  const rulesObj: Record<string, unknown> = {};
  for (const entry of config.rules) {
    if (entry.options && Array.isArray(entry.options) && entry.options.length > 0) {
      rulesObj[entry.ruleName] = [entry.severity, ...entry.options];
    } else {
      rulesObj[entry.ruleName] = entry.severity;
    }
  }
  configObj['rules'] = rulesObj;

  // Legacy output is strictly JSON. Unmappable rules cannot be encoded
  // inside the JSON without breaking JSON.parse, so they are omitted
  // here. Callers that want to surface them should use
  // formatUnmappableSummary() and write to stderr or a sidecar path.
  return JSON.stringify(configObj, null, 2);
}

/**
 * Build a human-readable summary of unmappable rules.
 *
 * Returns an empty string when there are no unmappable rules. Otherwise
 * returns a multi-line block listing each rule's id, reason, and the
 * original instruction text. Safe to print to stderr or write alongside
 * the legacy JSON output as a sidecar file.
 *
 * @param config - The mapped ESLint config
 * @returns A summary block or empty string when nothing is unmappable
 */
export function formatUnmappableSummary(config: EslintConfig): string {
  if (config.unmappable.length === 0) {
    return '';
  }
  const lines: string[] = [
    'Unmappable rules (not enforceable by ESLint):',
  ];
  for (const rule of config.unmappable) {
    lines.push(`  [${rule.sourceRuleId}] ${rule.reason}`);
    lines.push(`    Original: ${rule.sourceText}`);
  }
  return lines.join('\n');
}

/**
 * Serialize an EslintConfig to a runnable ESLint configuration string.
 *
 * Flat config produces valid ES module JavaScript with plugin imports
 * and a proper `export default [...]` structure. Legacy config produces
 * valid JSON suitable for .eslintrc.json files.
 *
 * @param config - The mapped ESLint config
 * @param format - Output format: 'flat' (default) or 'legacy'
 * @returns A string containing the ESLint configuration
 */
export function emitEslintConfig(config: EslintConfig, format: EslintFormat = 'flat'): string {
  if (format === 'legacy') {
    return emitLegacyConfig(config);
  }
  return emitFlatConfig(config);
}